name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true

    - name: Run tests
      run: go test -v ./...

    - name: Check code formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not formatted properly:"
          gofmt -l .
          exit 1
        fi